# Machine Learning - Data Preprocessing.
----------------------------------------

Data Preprocessing - Data preprocessing is one of the most vital steps in creating the machine learning models. This will be the starndard process that needs to be done on any dataset for creating any model that we want. 

## Import the essential libraries.

	1.> Numpy - The library containts mathematial tools. We use this library to include any mathematical calculations in our code. 	
	2.> Matplotlib.pyplot - library to help us create nice charts in python.  
	3.> Pandas library - library to import and manage datasets. 

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [2]:
dataset = pd.read_csv('/home/abhishek/projects/machine-learning/Data.csv')
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

From this data we want to create a Matrix of Features and Dependent variable vector. Matrix of features means all the data that we need to take the decision or the independent variable. We will do it use the code X = dataset.iloc[:,:-1].values. Here : means all and :-1 means all but last. 

In [3]:
X = dataset.iloc[:,:-1].values
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

Lets now create the dependent Variable Vector. which will be the last column which will be Y = dataset.iloc[:,3].values

In [4]:
Y = dataset.iloc[:,3].values
Y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

## Handle Missing Data
We can see from the data above that there is missing data that we need to handle for our ML model to run correctly. In the above dataset we can see that we have one missing data in the Age column and one missing data in the salary column. We do not want to delete the row as it might containt crutial data. Another way is to handle the missing data is by taking the mean of the values in the column and putting it there. We will use the imputer class from Scikitlearn library. 

Imputer takes some parameters, missing values = 'NaN', Strategy = 'mean' and axis

We will use imputer only on the data that we want to use it on. Upper bound is excluded. 

Use the transform method of the imputer class to takeout the mean. 

In [5]:
from sklearn.preprocessing import Imputer
imputer = Imputer(missing_values = 'NaN', strategy = 'mean', axis = 0)
imputer = imputer.fit(X[:,1:3])
X[:,1:3] = imputer.transform(X[:, 1:3])
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

As you can see that the missing data is now replaces with the mean. We can take other strategies also. We could use median or the most used value as well. 

## Categorical Data
We have to take care of the categorical data while working on a ML model. In the above dataset we can see that there are two Columns where we have text input which has categorical data. 

1.> Countries has 3 categories [France, Spain, Germany] 
2.> Purchased has 2 categories [Yes, No]

Since while creating mathematical models we can create formulas which will take only numerical data we need to convert this data into the Numerical Data. We need to encode the two variables. 

In [7]:
# Encoding Categorical Data. 
from sklearn.preprocessing import LabelEncoder
labelencoder_X = LabelEncoder()
labelencoder_X.fit_transform(X[:,0]) 


array([0, 2, 1, 2, 1, 0, 2, 0, 1, 0])

Now we need to replace this array with the first column. So all we need to do it. 

In [9]:
X[:,0] = labelencoder_X.fit_transform(X[:,0])
X

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 63777.77777777778],
       [0, 35.0, 58000.0],
       [2, 38.77777777777778, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

Now we have got our first column as all numbers but this is still not suffecient. Our formulas might take 0,1&2 as seperate values where they are just two seperate entities. So we need to prevent the machine learning algorithm from thining that one country is greater than the other. So we will introduce Dummy Variables which will have differnt columns for all the different rows. 1 means where they are present. 0 means they are not present there. 

We will use onehotencoder to create the dummy variables. 

In [14]:
from sklearn.preprocessing import OneHotEncoder
onehotencoder = OneHotEncoder(categorical_features = [0])
X = onehotencoder.fit_transform(X).toarray()
X

array([[1.00000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 4.40000000e+01, 7.20000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        1.00000000e+00, 2.70000000e+01, 4.80000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        0.00000000e+00, 3.00000000e+01, 5.40000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        1.00000000e+00, 3.80000000e+01, 6.10000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        0.00000000e+00, 4.00000000e+01, 6.37777778e+04],
       [1.00000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 3.50000000e+01, 5.80000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        1.00000000e+00, 3.87777778e+01, 5.20000000e+04],
       [1.00000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 4

In [17]:
labelencoder_Y = LabelEncoder()
Y = labelencoder_Y.fit_transform(Y)
Y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

So we have now transformed all the data into numerical data. In out program we are storing all the values in the variables, dataset, X,Y. Lets look at their values. 

In [18]:
dataset, X, Y

(   Country   Age   Salary Purchased
 0   France  44.0  72000.0        No
 1    Spain  27.0  48000.0       Yes
 2  Germany  30.0  54000.0        No
 3    Spain  38.0  61000.0        No
 4  Germany  40.0      NaN       Yes
 5   France  35.0  58000.0       Yes
 6    Spain   NaN  52000.0        No
 7   France  48.0  79000.0       Yes
 8  Germany  50.0  83000.0        No
 9   France  37.0  67000.0       Yes,
 array([[1.00000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 4.40000000e+01, 7.20000000e+04],
        [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         1.00000000e+00, 2.70000000e+01, 4.80000000e+04],
        [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 1.00000000e+00,
         0.00000000e+00, 3.00000000e+01, 5.40000000e+04],
        [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         1.00000000e+00, 3.80000000e+01, 6.10000000e+04],
        [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 1.00000000e

## Splitting the data into Training set and Test Set

For every Machine Learning model it is going to learn something from the correlation. Too much corelation is not good. That might not work if the data is slightly different. That we will see do later. The performance on the test set should not be very different from training set.  

We'll use the library train_test_split from sklean.crossvalidation. 

In [19]:
#Splitting the data into training set and Test Set
from sklearn.cross_validation import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.2, random_state = 0)

/home/abhishek/anaconda3/lib/python3.6/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [20]:
X_train, X_test, Y_train, Y_test

(array([[0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 1.00000000e+00,
         0.00000000e+00, 4.00000000e+01, 6.37777778e+04],
        [1.00000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 3.70000000e+01, 6.70000000e+04],
        [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         1.00000000e+00, 2.70000000e+01, 4.80000000e+04],
        [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         1.00000000e+00, 3.87777778e+01, 5.20000000e+04],
        [1.00000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 4.80000000e+01, 7.90000000e+04],
        [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         1.00000000e+00, 3.80000000e+01, 6.10000000e+04],
        [1.00000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 4.40000000e+01, 7.20000000e+04],
        [1.00000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
         0

So based on the above corelation the machine learning model will be able to predict based on the training set. It will take the decision on the test set. 

## Feature Scaling

A lot of machine learning models are based on a concept called the euclidean distance which means is the distance between the two points in a graph. In the above dataset the sqared difference between the salaries is much higher than the squared differnce between the age. 

In a situation like this when we are creating the machine learning model, It is going to completely ignore the age variable because its soo small. 

To solve this we will convert the variables into something which is scalable. and both the columns will be turned into number from -1 to +1

<img src = 'ed.jpg', width=400, height=500>

In [22]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)


In [23]:
X_train,X_test

(array([[-1.        ,  1.        , -1.        ,  2.64575131, -0.77459667,
          0.26306757,  0.12381479],
        [ 1.        , -1.        ,  1.        , -0.37796447, -0.77459667,
         -0.25350148,  0.46175632],
        [-1.        ,  1.        , -1.        , -0.37796447,  1.29099445,
         -1.97539832, -1.53093341],
        [-1.        ,  1.        , -1.        , -0.37796447,  1.29099445,
          0.05261351, -1.11141978],
        [ 1.        , -1.        ,  1.        , -0.37796447, -0.77459667,
          1.64058505,  1.7202972 ],
        [-1.        ,  1.        , -1.        , -0.37796447,  1.29099445,
         -0.0813118 , -0.16751412],
        [ 1.        , -1.        ,  1.        , -0.37796447, -0.77459667,
          0.95182631,  0.98614835],
        [ 1.        , -1.        ,  1.        , -0.37796447, -0.77459667,
         -0.59788085, -0.48214934]]),
 array([[-1.        ,  1.        , -1.        ,  2.64575131, -0.77459667,
         -1.45882927, -0.90166297],
        

^ Now all our data is Feature scaled. 